import Head from 'next/head';
import Layout from './layout';
import HomePage from './home/home';

export default function Home() {
  return (
    <div>
      <Head>
        <title>World Pranic Healing</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href='/images/logo_cropped.png' />
        <link rel='apple-touch-icon' href='/images/logo_cropped.png' />
      </Head>
      <Layout title='World Pranic Healing'>
        <HomePage />
      </Layout>
      <script src='/js/navbar.js' async></script>
    </div>
  );
}
